### ISSUE TITLE
Calendar redesign

### ISSUE THREAD

**Issue by pzmarzly** [nokia-wroclaw/innovativeproject-check-room#28]
- [x] Currently we display too much information - our main focus should be Mon-Fri 8-to-5, though users should be able to see all week. We should somehow make parts of calendar collapsible.
- [x] We should display 15-minute long events correctly. We can assume events are never overlapping, but what to do if e.g. there are 2 5-minute long events that fall into the same tile?
- [x] We need a compact weekly view for mobile.
- [x] Optional: in case of an event spanning over multiple days (we don't support that scenario), we shouldn't create a field where end time <= start time.

**Comment by oleks12345** [comment]
even google calendar doesn't really handle displaying long events, they just display them on top,we can thing about something like that 
![image](https://user-images.githubusercontent.com/19672992/78595155-cddd4e80-7849-11ea-87ea-212704e70c1e.png)

**Comment by oleks12345** [comment]
they also have problem with short events (5 min)
![image](https://user-images.githubusercontent.com/19672992/79395952-1815ac80-7f7b-11ea-9d7d-7131ae3b4c2e.png)

**Comment by pzmarzly** [comment]
Fixed by #31 and #32 .
