### ISSUE TITLE
Husky config issue

### ISSUE THREAD

**Issue by pzmarzly** [nokia-wroclaw/innovativeproject-check-room#3]
When running `git commit` from the CLI, we get:

```text
⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index.
```

@oleks12345 please check if `git add` can be removed from both `package.json` files.

**Comment by oleks12345** [comment]
I'm aware of it, git add is in that config from exact that reason: after eslint formats and fix files, that fixed files should be committed, not ones before linting

**Comment by pzmarzly** [comment]
Yes, but as far as I understand, git add is run automatically by git itself after running a hook (and to be honest, I can't think of any situation where someone would want it to work otherwise, so that makes it a sane default)
