### ISSUE TITLE
Docker - research

### ISSUE THREAD

**Issue by pzmarzly** [nokia-wroclaw/innovativeproject-check-room#4]
* https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
* https://docs.docker.com/get-started/

**Comment by pzmarzly** [comment]
- https://stackoverflow.com/questions/55981496/travisci-with-npm-run-test-from-create-react-app

**Comment by oleks12345** [comment]
https://hub.docker.com/_/node/

**Comment by pzmarzly** [comment]
Closed by #19 - server connects to Google API, so we consider the deployment process complete.
