### ISSUE TITLE
CI/CD and heroku - research

### ISSUE THREAD

**Issue by pzmarzly** [nokia-wroclaw/innovativeproject-check-room#5]
- https://docs.travis-ci.com/user/deployment/heroku/

**Comment by pzmarzly** [comment]
I'm working on it in my fork.

Please note that free Travis accounts are limited to 1 parallel build. We should try to make our script parallel-aware, to make sure an upgrade to paid account won't break our CI.

**Comment by oleks12345** [comment]
https://jojozhuang.github.io/tutorial/react-app/continuously-deploy-full-stack-react-app-to-heroku-with-travis-ci/

**Comment by pzmarzly** [comment]
https://medium.com/@adamwheatley_61937/continuous-integration-with-angular-5-travis-docker-and-heroku-eb93d58e9352

**Comment by pzmarzly** [comment]
Closed by #19 - server connects to Google API, so we consider the deployment process complete.
